### ISSUE TITLE
Document Policy for Supporting Compilers/Runtimes

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi-docker-containers#103]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This repository offers container images for all of our supported languages. However, we don't provide documentation of what version of the language is installed on the container image. 

**We want customers to know our policy for upgrading the compilers/runtimes associated with each language.** 
This has two primary benefits:

1. It allows customers who rely on these images but run old versions of the language to know how much time they have to upgrade. For example, support a customer is running Go 1.18. They may want to know when we plan to bump the version of this Go image from 1.18 to 1.19 so they can prepare their source code to be compatible with 1.19. In the case of Go, this isn't too much of a problem since the Go compatibility promise guarantees straightforward upgrading. However, for languages like NodeJS, this is not the case.

2. It establishes a timeline for us to upgrade the container images. We want to know when we can upgrade the images without breaking our customers' programs.

As an ancillary benefit, documenting the upgrade policy increases our accountability. Right now, container images seem to be inconsistently upgraded across languages. For example, the Go version [is pinned to 1.18](https://github.com/pulumi/pulumi-docker-containers/blob/main/docker/go/Dockerfile#L9), but our NodeJS runtime [floats to whatever is LTS](https://github.com/pulumi/pulumi-docker-containers/blob/main/docker/nodejs/Dockerfile#L18). 

You can see we won't specify the language version in our Dockerhub documentation ([Go](https://hub.docker.com/r/pulumi/pulumi-go), for example).

### Affected area/feature

* Dockerhub Documentation
* The Dockerfile ARGs themselves
* This repo's README

**Comment by julienp** [comment]
This now documented in https://github.com/pulumi/pulumi-docker-containers?tab=readme-ov-file#language-versions
