### ISSUE TITLE
.NET installed under /root/.dotnet is inaccessible when run as non-root

### ISSUE THREAD

**Issue by polivbr** [pulumi/pulumi-docker-containers#113]
### What happened?

The .NET install was changed to use the dotnet-install.sh script, which by default installs .NET under $HOME/.dotnet, or /root/.dotnet in the case of the docker builds. 

When running the container as a non-root user, as is done by the pulumi kubernetes operator, this directory is inaccessible and dotnet cannot be executed.

### Steps to reproduce

Run the pulumi docker image as non-root (via the kubernetes operator as an example).

### Expected Behavior

dotnet is executed as expected.

### Actual Behavior

The following error is reported when running pulumi:

could not find `dotnet` on the $PATH: exec: "dotnet": executable file not found in $PATH

### Additional context

The install script takes an --install-dir argument that can be used to install .NET into a system-wide location.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by martinmesserli** [comment]
I ran into the same issue and therefore cannot use a dotnet Pulumi stack for deployment in a Git repo. Is there any fix available soon?

**Comment by justinvp** [comment]
Closing out some old issues. This was fixed by https://github.com/pulumi/pulumi-docker-containers/pull/161
