### ISSUE TITLE
Pulumi/Pulumi does not use Pulumi/Base

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi-docker-containers#114]
### What happened?

The `pulumi/pulumi` image uses `python` as a base image.

Ideally, we'd like `pulumi/pulumi` (a.k.a. the kitchen sink image) to share layers with the base image, so that caching the base image speeds up downloading the kitchen sink image. This is useful in contexts where one cluster is deploying both the kitchen sink image and the base image.

### Steps to reproduce

Inspect the shared layers between `pulumi/pulumi` and `pulumi/base` and see that no layers are shared.

### Expected Behavior

Expected the kitchen sink docker image to start with (on line 16):

```dockerfile
FROM pulumi/pulumi-base:${PULUMI_VERSION}
```

### Actual Behavior

It actually starts with `FROM debian:11-slim`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by julienp** [comment]
This doesn't provide us too much now that the base image starts with Debian.
