### ISSUE TITLE
[feature request] docker images for linux/arm64

### ISSUE THREAD

**Issue by runlevel5** [pulumi/pulumi-docker-containers#12]
pulumi has been working nicely on Linux (ARM64) for few months. I would like to ask why there is no official docker images of pulumi for linux/arm64?

**Comment by jkodroff** [comment]
@runlevel5 One more question: Would Debian-only arm64 images be sufficient, or do you specifically need UBI?  We're having quite a bit of trouble getting UBI to build for nodejs on arm64.
