### ISSUE TITLE
Cannot Sync New Providers Image to ECR

### ISSUE THREAD

**Issue by RobbieMcKinstry** [pulumi/pulumi-docker-containers#122]
### What happened?

We added a new container image to the `pulumi-docker-containers` repo recently.  The image is for building providers (basically, it's the Kitchen Sink + TF Gen + Goreleaser).

There's a failing build for this new image when it tried to upload to ECR. As a knock-on effect, the way the Action is written will cancel parallel builds when one of them fails. Therefore, the job to upload the Kitchen Sink image failed too.

[Judging by the build logs](https://github.com/pulumi/pulumi-docker-containers/actions/runs/3501546534/jobs/5865289220#step:4:96), the reason for the failure appears to be that the `ServiceAccount` used by this script isn't authorized to upload the image.

I suppose I would also expect to have to create a new ECR repo (DockerHub has already succeeded once, and GitHub Packages should automatically create it on our behalf I think) for the image too.

I expect this to be blocking for the scheduled release on Wednesday, since the Kitchen Sink image should be released in lock-step with the CLI. I'm marking this as P1 as I think it's a release blocker.

## Possible Solutions

**The real solution** is to give the ServiceAccount the permissions it needs and create the ECR repo.

A quick workaround would be either...
1. Run these workflows sequentially, upload the Kitchen Sink image first. That way, the Providers image should fail but the Kitchen Sink image will succeed. 
2. Pass the build even if the Providers image fails to upload, so the Kitchen Sink image could continue to run in parallel.

## References

* [Other context from Slack.](https://pulumi.slack.com/archives/C5J0XFWRJ/p1669015591254599)
* Successful upload for DockerHub Providers image https://hub.docker.com/r/pulumi/pulumi-provider-build-environment

### Steps to reproduce

Inspect build logs: https://github.com/pulumi/pulumi-docker-containers/actions/runs/3501546534/jobs/5865289220#step:4:96

### Expected Behavior

Public ECR upload of Providers image to succeed. Build to pass.

### Actual Behavior

Build failed and so did the upload.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Fixed by https://github.com/pulumi/get.pulumi.com/pull/143
