### ISSUE TITLE
pulumi container missing gke-gcloud-auth-plugin

### ISSUE THREAD

**Issue by jjhuff** [pulumi/pulumi-docker-containers#123]
### What happened?

I was trying to bring up a GKE-based project and the k8s provider/kubectl complained about missing `gke-gcloud-auth-plugin`.

### Steps to reproduce

Run one of the gke examples

### Expected Behavior

`gke-gcloud-auth-plugin` exists

### Actual Behavior

`gke-gcloud-auth-plugin` doesn't exist

### Additional context

https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

Seems like since the mega container contains `gcloud`, that iut should also include `gke-gcloud-auth-plugin`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by Frassle** [comment]
Seems reasonable, given we've already got gcloud looks like its just a call to `gcloud components install gke-gcloud-auth-plugin`
