### ISSUE TITLE
Missing `-debian` tag since version 3.55.0

### ISSUE THREAD

**Issue by 1oglop1** [pulumi/pulumi-docker-containers#129]
### What happened?

Since image version 3.55.0 there are new tags
However `-debian` tag does not exist anymore, thus this is not true 

https://github.com/pulumi/pulumi-docker-containers/blob/604a9532da4a0ff1c828fe107e42ec5a5d48de65/README.md?plain=1#L24

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/7480694/222925625-57a9885e-5be4-42e2-a498-a960a261e4c8.png">

### Expected Behavior

Reintroduce back `-debian` tag?

### Steps to reproduce

-

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hey, thanks for filing this. I'm currently working on #127 which documents that these images were missing.

I've just run a workflow to add 3.56.0-debian as seen here
https://hub.docker.com/layers/pulumi/pulumi-nodejs/3.56.0-debian/images/sha256-03c6789371d25370f6f7cbd9a963c085279bf41ee38de09dbe025a32a2130dd3?context=explore

I'm currently in the process of backfilling the 3.54.0 and 3.55.0 for some of the images that were not pushed correctly.

**Comment by dixler** [comment]
I believe this should be fixed as of now. LMK if it's not. :slightly_smiling_face:
