### ISSUE TITLE
Azure CLI can't be installed in latest Pulumi docker image

### ISSUE THREAD

**Issue by durist** [pulumi/pulumi-docker-containers#142]
### What happened?

The docs state that the Debian images are based on the buster release, but that no longer appears to be the case; here's the release info for the current image:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm


```
This makes it impossible to install the azure CLI in the image. Attempting to install from Microsoft's package fails with this error:
```
The following packages have unmet dependencies:
 azure-cli : Depends: libffi7 (>= 3.3~20180313) but it is not installable
             Depends: libssl1.1 (>= 1.1.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```
This happens even when setting "AZ_REPO=bullseye"  per Microsoft's docs: [https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)

### Expected Behavior

az CLI should be installable in Pulumi Docker image

### Steps to reproduce

[https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt](https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt)

### Output of `pulumi about`

$ pulumi about
CLI          
Version      3.72.2
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME                      VERSION
azure-native              1.103.0
azuread                   5.38.0
kubernetes                3.29.1
kubernetes-ingress-nginx  0.0.10
python                    unknown

Host     
OS       debian
Version  12.0
Arch     x86_64

This project is written in python: executable='/usr/local/bin/python3' version='3.9.17
'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/durist
User           durist
Organizations  durist, UCAR

Dependencies:
NAME                             VERSION
pip                              23.1.2
pulumi-azure-native              1.103.0
pulumi-azuread                   5.38.0
pulumi-kubernetes-ingress-nginx  0.0.10
setuptools                       68.0.0
sshkey-tools                     0.10.1
wheel                            0.40.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hey, I'm checking with the author of the commit for some more context around the change, but it looks to be introduced in this change:

https://github.com/pulumi/pulumi-docker-containers/commit/cdb8187a21aa58d5de8d8b4c1c395466d61d7c3a

**Comment by julienp** [comment]
This was fixed in https://github.com/pulumi/pulumi-docker-containers/pull/214
