### ISSUE TITLE
Release builds since #116 are failing

### ISSUE THREAD

**Issue by tferazzi** [pulumi/pulumi-docker-containers#143]
### What happened?

All release builds since version 3.71.0 are failing, therefore there are outdated images (as well as language specific images) on all registries:
- [AWS ECR Public Gallery](https://gallery.ecr.aws/pulumi/pulumi)
- [Github Container Registry](https://github.com/orgs/pulumi/packages/container/package/pulumi)
- [DockerHub](https://hub.docker.com/r/pulumi/pulumi/tags)

Latest version in all registries is 3.71.0 while the latest release is at [3.72.2](https://github.com/pulumi/pulumi/releases)

### Expected Behavior

To have the latest pulumi versions available as images.

### Steps to reproduce

See the [release pipeline](https://github.com/pulumi/pulumi-docker-containers/actions/workflows/release.yml).

### Output of `pulumi about`

CLI
Version      3.72.2
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  13.4
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
The issue seems to be:

https://github.com/pulumi/pulumi-docker-containers/actions/runs/5350628116/jobs/9820838240#step:6:9113

```
E: The repository 'https://packages.microsoft.com/repos/azure-cli bookworm Release' does not have a Release file.
```

Seems to be related to https://github.com/Azure/azure-cli/issues/26686

Debian "bookworm" was released June 10, after which we started failing. Before that, it was using Debian "bullseye".

**Comment by justinvp** [comment]
We could workaround by installing via pip, but then we hit another issue installing Java:

https://github.com/pulumi/pulumi-docker-containers/actions/runs/5405972454/jobs/9822608465?pr=145#step:6:10786

```
ERROR: failed to solve: process "/bin/sh -c apt-get update -y &&   apt-get install -y       gradle       maven" did not complete successfully: exit code: 100
```

```
27.08 Errors were encountered while processing:
27.08  ca-certificates-java
27.12 E: Sub-process /usr/bin/dpkg returned an error code (1)
```

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030129
