### ISSUE TITLE
Publish several `PYTHON_VERSION` images

### ISSUE THREAD

**Issue by LouisAmon** [pulumi/pulumi-docker-containers#144]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The current implementation doesn't specify the `PYTHON_VERSION` (which by default is 3.9) : it's a shame because the argument is there in the Dockerfile, but it's not present in a matrix in the GitHub Actions CI to build & push multiple images according to that argument.

I'm going to try and build my own custom images, but I wanted to raise this issue as it hinders the adoption of Pulumi Deployments.

At my company we mainly use Python 3.11

### Affected area/feature

Pulumi Deployments

**Comment by dixler** [comment]
Thanks for letting us know. The feedback is very helpful.

**Comment by justinvp** [comment]
This has now been addressed. For Python, we now have images for 3.9 through 3.12 https://hub.docker.com/u/pulumi?page=1&search=pulumi-python. The default image (without suffix) `pulumi/pulumi-python` still uses 3.9, but we will start updating this and other languages to track the latest stable version of each language in November. For more details see https://www.pulumi.com/blog/docker-containers.
