### ISSUE TITLE
Switch back to `python:3.9-slim` image when upstream issues with Debian "bookworm" are addressed

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-docker-containers#147]
Debian "bookworm" was released June 10 and is used by the `python:3.9-slim` image. Unfortunately, there are a couple issues blocking use of "bookworm" for us:

1. https://github.com/Azure/azure-cli/issues/26686. Debian bookworm isn't yet supported (although, we could workaround by installing the azure-cli via pip)
2. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030129. Installing Java is failing.

To workaround these issues, in the meantime, we'll "pin" back to using Debian "bullseye" by using the `python:3.9-slim-bullseye` base image. When the above upstream issues are fixed, we should consider switching back to using `python:3.9-slim".

Background: https://github.com/pulumi/pulumi-docker-containers/issues/143

**Comment by julienp** [comment]
For kitchen sink this is happening as part of https://github.com/pulumi/pulumi-docker-containers/pull/232
