### ISSUE TITLE
Inconsistent Node versions between images, not using latest LTS

### ISSUE THREAD

**Issue by kerruba-milkman** [pulumi/pulumi-docker-containers#148]
### What happened?

I'm using the docker images to run applications using nodejs.
The `pulumi/pulumi` image uses node `v16.20.1`, while the `pulumi/pulumi-nodejs` uses `v18.16.0`.

### Expected Behavior

I was expecting to see the same node version across the different images. Moreover,  both the images are not using the current node LTS version.

### Steps to reproduce

```bash
docker run -it --entrypoint node public.ecr.aws/pulumi/pulumi-nodejs --version
docker run -it --entrypoint node public.ecr.aws/pulumi/pulumi --version
```

### Output of `pulumi about`

```
CLI
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Host
OS       ubuntu
Version  22.04
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dixler** [comment]
Hi, taking a look into this.

**Comment by EvanBoyle** [comment]
Node 16 is EOL in 11 days, marking this as P1. 

We also have references to node 14, but I'm not sure if it actually gets used anywhere. https://github.com/pulumi/pulumi-docker-containers/blob/main/docker/nodejs/dnf/nodejs.module#L3
