### ISSUE TITLE
Pulumi Login into S3 backend fails

### ISSUE THREAD

**Issue by bvspavan6** [pulumi/pulumi-docker-containers#183]
### What happened?

I am trying to move to Pulumi from AWS CDK. I have been trying to automate connecting to S3 Backend using pulumi/pulumi-go docker image. So far wasted 2 full days and unsuccessful. Could not find documentation.
I am trying to setup Pulumi via Automation, without using CLI
Basically, I cannot do a pulumi login to S3 inside pulumi-go docker image -  This fails with user not found message. Pls help
I added a bash script as start of the container 

### Example

```bash
#!/bin/bash
set -eux

ROLE_ARN="${AWS_ROLE_ARN}"
SERVICE_ACCOUNT_TOKEN_PATH="${AWS_WEB_IDENTITY_TOKEN_FILE}"

if [ -f "$SERVICE_ACCOUNT_TOKEN_PATH" ]; then
    TOKEN=$(cat "$AWS_WEB_IDENTITY_TOKEN_FILE")
    echo "Kubernetes Service Account Token: $TOKEN"
else
    echo "Service account token not found at $SERVICE_ACCOUNT_TOKEN_PATH"
    exit 1
fi
	
BUCKET_NAME="XXXXYYYY"

assume_role() {
    echo "Assuming role..."

    credentials=$(aws sts assume-role-with-web-identity --role-arn "$ROLE_ARN" --role-session-name "pulumi-assume-role-session" --web-identity-token "$TOKEN" --output json)
    export AWS_ACCESS_KEY_ID=$(echo "$credentials" | jq -r .Credentials.AccessKeyId)
    export AWS_SECRET_ACCESS_KEY=$(echo "$credentials" | jq -r .Credentials.SecretAccessKey)
    export AWS_SESSION_TOKEN=$(echo "$credentials" | jq -r .Credentials.SessionToken)
    echo "assume role completed.."
    echo $AWS_ACCESS_KEY_ID
    echo $AWS_SECRET_ACCESS_KEY
}

pulumi_login() {
    echo "Logging in to Pulumi..."
    pulumi login "s3://$BUCKET_NAME?region=us-east-1&awssdk=v2"
}

main() {
    assume_role
    echo "pulumi Login "
    pulumi_login
  
}

main
export MYAPP="orchestrator"
echo "Running  outside main Orchestrator"
echo $MYAPP
exec /app/bin/orchestrator
```

### Output of `pulumi about`

```
CLI
Version      3.108.1
Go Version   go1.22.0
Go Compiler  gc

Host
OS       debian
Version  11.9
Arch     x86_64

Pulumi locates its logs in /tmp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /pulumi/projects). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: Could not access the backend: could not get cloud url: failed to get the home path: getting current user: luser: unable to get current user
```

### Additional context

I am trying to setup Pulumi via Automation, without using CLI. 
Also tried running below to setup  before calling `UpsertStackInlineSource`

```go
_, err := aws.NewProvider(ctx, "named-provider", &aws.ProviderArgs{
		AssumeRoleWithWebIdentity: &aws.ProviderAssumeRoleWithWebIdentityArgs{
			RoleArn:              pulumi.String(arn),
			WebIdentityTokenFile: pulumi.String(tokenFile),
		}})
		
			vpc := &awscloud.VPC{
		Name:                    "test-vpc",
		CidrBlock:               "10.0.0.0/8",
		Region:                  "eu-west-1",
		PublicSubnetCidrBlocks:  []string{"10.1.0.0/24", "10.2.0.0/24"},
		PrivateSubnetCidrBlocks: []string{"10.3.0.0/24", "10.4.0.0/24"},
	}

	opts := []auto.LocalWorkspaceOption{
		auto.Project(workspace.Project{
			Name:    tokens.PackageName(projectName),
			Runtime: workspace.NewProjectRuntimeInfo("go", nil),
			Main:    cwd,
			Backend: &workspace.ProjectBackend{
				URL: "XXXYYY",
			},
		},
		),
	}

	stack, err := auto.UpsertStackInlineSource(ctx, stackName, projectName, vpc.Run, opts...)
	if err != nil {
		log..fatalf("Failed to load dev stack: %s\n", err)
	}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by justinvp** [comment]
Hi @bvspavan6, sorry for the delay and trouble here. Are you still having problems with `pulumi login`? Does it work for you outside of the container? What's the exact error returned from `pulumi login`?

**Comment by mikhailshilkov** [comment]
Based on the information provided, there are a few potential issues with the user's setup:

1. The error message "could not get cloud url: failed to get the home path: getting current user: luser: unable to get current user" suggests there might be an issue with the user permissions or authentication within the Docker container.
2. The warning "Failed to read project: no Pulumi.yaml project file found" indicates that Pulumi is not finding the expected project configuration file. This could be due to running the command in the wrong directory or not properly setting up the Pulumi project structure.
3. The user mentions trying to use Pulumi's Automation API, but the bash script seems to be using CLI commands. There might be a mismatch somewhere here.

Since this issue is six months old and we haven't heard back, I'll go ahead and close it as non-actionable. If you still need assistance, please let us know.
