### ISSUE TITLE
Python 3.12 and Poetry variants

### ISSUE THREAD

**Issue by olafurnielsen** [pulumi/pulumi-docker-containers#205]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

- The Python runner image is using the Python 3.9 base image despite 3.12 being the newest major release since October last year
- A lot of typing improvements have been introduced in recent Python versions
- After https://github.com/pulumi/pulumi/pull/16315 was added Poetry needs to be included (or made available in a seperate variant) for that to be properly supported 

### Affected area/feature

- Build pipelines

**Comment by olafurnielsen** [comment]
Note: There's already an open PR https://github.com/pulumi/pulumi-docker-containers/pull/160 which adds 3.10 and 3.11 and should be simple to add 3.12 to that build matrix.

**Comment by justinvp** [comment]
Thanks for opening this! We are planning to add support for 3.12 as part of #204. Including Poetry in the Python (and "kitchen sink") makes sense to me.

**Comment by julienp** [comment]
Poetry now ships in all of the Python images, and we introduced version images https://hub.docker.com/u/pulumi?page=1&search=pulumi-python

If you want to use Python 3.12 today, you can use the `pulumi/pulumi-python-3.12` image.

We'll have an announcement with a timeline for updating the default from 3.9 to 3.12 (or 3.13 depending on the timing) soon.
