### ISSUE TITLE
pulumi-go image tag does not match installed version of Pulumi

### ISSUE THREAD

**Issue by pyoio** [pulumi/pulumi-docker-containers#71]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

The latest (at time of writing) tag on the pulumi-go docker image is reporting an older version via `pulumi version` on the command line.

```
> docker run -it --rm pulumi/pulumi-go:3.18.1 pulumi version

Unable to find image 'pulumi/pulumi-go:3.18.1' locally
3.18.1: Pulling from pulumi/pulumi-go
Digest: sha256:93aa1a8c33d73b073b50b20aec1b8f3ebcf3fc06c8fcef803139f74a9e16be63
Status: Downloaded newer image for pulumi/pulumi-go:3.18.1
v3.18.0

warning: A new version of Pulumi is available. To upgrade from version '3.18.0' to '3.18.1', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

Expected: The version to be 3.18.1
Actual: The version was 3.18.0

**Comment by jkodroff** [comment]
@pyoio Just to confirm, you pulled this from Docker Hub (as opposed to the AWS ECR public gallery)?

**Comment by jkodroff** [comment]
Isolated this issue specifically to the `pulumi-go` image.

**Comment by pyoio** [comment]
> @pyoio Just to confirm, you pulled this from Docker Hub (as opposed to the AWS ECR public gallery)?

that's correct
