### ISSUE TITLE
Make language interpreter versions more discoverable

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-docker-containers#86]
We base our sdk images off upstream SDK specific images.

Around pulumi version 3.24.1 our chosen image node image `node:lts-bullseye-slim` had its node version upgraded underneath us.

It'd be great if we could either:

- pin to explicit versions so we can announce to customers when things are changing
- make the underlying language interpreter more discoverable, perhaps via labels?

**Comment by RobbieMcKinstry** [comment]
Related: https://github.com/pulumi/pulumi-docker-containers/issues/103

We'll document our support and upgrade policy, and around that time, we can tackle this issue too. Right now, this repo is not compatible with our brand-spankin'-new support policy. (DM me on Slack for the internal link.)

**Comment by julienp** [comment]
We now have a clear version policy and a set of language-runtime-versioned images. See https://github.com/pulumi/pulumi-docker-containers?tab=readme-ov-file#language-versions
