### ISSUE TITLE
Add Java support

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-docker-containers#88]
We need to add Java support in our containers:

* Add a Java runtime to the `pulumi` "kitchen sink" image
* Create a `pulumi-java` image

**Comment by AaronFriel** [comment]
@dixler can you also look into what it would take to add the Eclipse JVM to the kitchen sink image?

**Comment by AaronFriel** [comment]
pulumi-java image tracked here: https://github.com/pulumi/pulumi-java/issues/529

@dixler please update this with a milestone when you get to it?
