### ISSUE TITLE
Upgrade Go runtime to 1.17.7 - BitBucket Go breaking change

### ISSUE THREAD

**Issue by GarthWood** [pulumi/pulumi-docker-containers#90]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

BitBucket has rolled out a breaking change for Go users and upgrades are needed as mentioned here:
[Changes to Bitbucket API Requires Latest Version of Go](https://community.atlassian.com/t5/Bitbucket-articles/Changes-to-Bitbucket-API-Requires-Latest-Version-of-Go/ba-p/1975819)

Looking at the Pulumi Go docker runtime version, it is using 1.17.3.

Can it be upgraded to 1.17.7?

**Comment by mikhailshilkov** [comment]
@dixler Could you please take a look?
